server:
  port: 8085
spring:
  main:
    banner-mode: off
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
      show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
    hibernate:
      ddl-auto: update
  #Swagger configuration #######################################################################################################
springdoc:
  swagger-ui:
   enabled: true
   path: /swagger-ui.html
   url: /swagger.yaml